name: "Purge Fastly cache"
description: "GitHub Actions to purge Fastly cache by surrogate key or URL."
author: "Yuku Kotani"
branding:
  icon: archive
  color: red
inputs:
  api-token:
    required: true
    description: "API token of Fastly"
  service-id:
    required: false
    description: "Service ID to purge. Required for `surrogate-key` target."
    default: ""
  soft:
    description: "If false, the affected object will be inaccessible rather than marked as stale."
    default: true
  target:
    required: true
    description: "Target to purge. Currently only `surrogate-key` and `single-url` are supported."
  keys:
    required: false
    description: "Surrogate keys to delete. Required if the target is `surrogate-key`."
    default: []
  url:
    required: false
    description: "Cached URL to purge. Required if the target is `single-url`."
    default: ""
  debug:
    description: "debug key"
    default: false

runs:
  using: "node12"
  main: "dist/index.js"
